# Generated by Django 3.1.5 on 2021-01-27 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateTimeField()),
                ('numero', models.CharField(max_length=16, unique=True)),
                ('data_nascimento', models.DateTimeField()),
                ('limite', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateTimeField()),
                ('ta_pago', models.BooleanField()),
                ('cartao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cartao')),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('valor', models.FloatField()),
                ('estabelecimento', models.CharField(max_length=30)),
                ('data', models.DateTimeField()),
                ('prestacoes_total', models.IntegerField()),
                ('prestacao_atual', models.IntegerField()),
                ('cartao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cartao')),
                ('fatura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fatura')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('renda', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='operacao',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.perfil'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.perfil'),
        ),
        migrations.AddField(
            model_name='cartao',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.perfil'),
        ),
    ]
