# Generated by Django 3.1.5 on 2021-01-28 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210127_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartao',
            options={'verbose_name_plural': 'Cartoes'},
        ),
        migrations.AlterModelOptions(
            name='operacao',
            options={'verbose_name_plural': 'Operacoes'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'Perfis'},
        ),
    ]
