# Generated by Django 3.1.5 on 2021-01-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210128_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartao',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='prestacao_atual',
        ),
        migrations.AlterField(
            model_name='cartao',
            name='data_emissao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='data_vencimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='data',
            field=models.DateField(),
        ),
    ]
