# Generated by Django 3.1.5 on 2021-01-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_operacao_fatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='fechada',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
