# Generated by Django 3.1.5 on 2021-01-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fatura_operacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
